{
	"version": 1782408470,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/play-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/lblevel1-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite43-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite45-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite51-sheet0.png",
		"images/sprite52-sheet0.png",
		"images/sprite53-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/sprite56-sheet0.png",
		"images/tamanajaib2-sheet0.png",
		"images/sprite57-sheet0.png",
		"images/sprite58-sheet0.png",
		"images/sprite59-sheet0.png",
		"images/sprite60-sheet0.png",
		"images/sprite61-sheet0.png",
		"images/sprite62-sheet0.png",
		"images/sprite63-sheet0.png",
		"images/sprite64-sheet0.png",
		"images/sprite65-sheet0.png",
		"images/sprite66-sheet0.png",
		"images/sprite67-sheet0.png",
		"images/sprite68-sheet0.png",
		"images/sprite69-sheet0.png",
		"images/sprite70-sheet0.png",
		"images/sprite71-sheet0.png",
		"images/sprite72-sheet0.png",
		"images/sprite73-sheet0.png",
		"images/sprite74-sheet0.png",
		"images/tamanajaib5-sheet0.png",
		"images/tamanajaib5-sheet1.png",
		"images/sprite75-sheet0.png",
		"images/sprite76-sheet0.png",
		"images/sprite78-sheet0.png",
		"images/sprite79-sheet0.png",
		"images/sprite80-sheet0.png",
		"images/tamanajaib12-sheet0.png",
		"images/sprite82-sheet0.png",
		"images/sprite83-sheet0.png",
		"images/sprite84-sheet0.png",
		"images/sprite85-sheet0.png",
		"images/sprite86-sheet0.png",
		"images/sprite90-sheet0.png",
		"images/sprite91-sheet0.png",
		"images/sprite92-sheet0.png",
		"images/sprite93-sheet0.png",
		"images/sprite98-sheet0.png",
		"images/sprite99-sheet0.png",
		"images/sprite100-sheet0.png",
		"images/sprite106-sheet0.png",
		"images/sprite107-sheet0.png",
		"images/sprite108-sheet0.png",
		"images/sprite109-sheet0.png",
		"images/sprite110-sheet0.png",
		"images/sprite111-sheet0.png",
		"images/sprite112-sheet0.png",
		"images/sprite113-sheet0.png",
		"images/number_blocks_01_set_5_64x64_-sheet0.png",
		"images/number_blocks_01_set_5_64x64_2-sheet0.png",
		"images/number_blocks_01_set_5_64x64_3-sheet0.png",
		"images/number_blocks_01_set_3_64x64_-sheet0.png",
		"images/number_blocks_01_set_3_64x64_2-sheet0.png",
		"images/number_blocks_01_set_3_64x64_3-sheet0.png",
		"images/angka9-sheet0.png",
		"images/7angka-sheet0.png",
		"images/5angka-sheet0.png",
		"images/angka2-sheet0.png",
		"images/angka3-sheet0.png",
		"images/angka6-sheet0.png",
		"images/angka7-sheet0.png",
		"images/angka5-sheet0.png",
		"images/3angka-sheet0.png",
		"images/sprite114-sheet0.png",
		"images/sprite115-sheet0.png",
		"images/sprite116-sheet0.png",
		"images/sprite118-sheet0.png",
		"images/sprite119-sheet0.png",
		"images/sprite120-sheet0.png",
		"images/sprite123-sheet0.png",
		"images/a4-sheet0.png",
		"images/a5-sheet0.png",
		"images/b1-sheet0.png",
		"images/b2-sheet0.png",
		"images/b3-sheet0.png",
		"images/c6-sheet0.png",
		"images/c8-sheet0.png",
		"images/a1-sheet0.png",
		"images/a8-sheet0.png",
		"images/b7-sheet0.png",
		"images/b9-sheet0.png",
		"images/c3-sheet0.png",
		"images/sprite129-sheet0.png",
		"images/sprite130-sheet0.png",
		"images/sprite131-sheet0.png",
		"images/sprite132-sheet0.png",
		"images/sprite133-sheet0.png",
		"images/sprite134-sheet0.png",
		"images/number_blocks_01_set_4_64x64_-sheet0.png",
		"images/number_blocks_01_set_4_64x64_2-sheet0.png",
		"images/number_blocks_01_set_2_64x64_10-sheet0.png",
		"images/sprite135-sheet0.png",
		"images/sprite136-sheet0.png",
		"images/tamanajaib16-sheet0.png",
		"images/sprite140-sheet0.png",
		"images/sprite141-sheet0.png",
		"images/sprite148-sheet0.png",
		"images/sprite162-sheet0.png",
		"images/sprite163-sheet0.png",
		"images/sprite164-sheet0.png",
		"images/sprite165-sheet0.png",
		"images/sprite166-sheet0.png",
		"images/sprite167-sheet0.png",
		"images/sprite168-sheet0.png",
		"images/sprite169-sheet0.png",
		"images/sprite171-sheet0.png",
		"images/sprite172-sheet0.png",
		"images/sprite173-sheet0.png",
		"images/sprite177-sheet0.png",
		"images/sprite177-sheet1.png",
		"images/sprite179-sheet0.png",
		"images/sprite180-sheet0.png",
		"images/sprite181-sheet0.png",
		"images/sprite183-sheet0.png",
		"images/sprite187-sheet0.png",
		"images/sprite188-sheet0.png",
		"images/sprite190-sheet0.png",
		"images/sprite193-sheet0.png",
		"images/sprite194-sheet0.png",
		"images/sprite196-sheet0.png",
		"images/sprite197-sheet0.png",
		"images/sprite198-sheet0.png",
		"images/sprite199-sheet0.png",
		"images/sprite200-sheet0.png",
		"images/sprite201-sheet0.png",
		"images/sprite202-sheet0.png",
		"images/sprite203-sheet0.png",
		"images/sprite204-sheet0.png",
		"images/sprite208-sheet0.png",
		"images/sprite211-sheet0.png",
		"images/sprite212-sheet0.png",
		"media/counting star parade.ogg",
		"media/huruf a.ogg",
		"media/huruf b.ogg",
		"media/huruf c.ogg",
		"media/huruf d.ogg",
		"media/huruf e.ogg",
		"media/huruf f.ogg",
		"media/huruf g.ogg",
		"media/huruf h.ogg",
		"media/huruf i.ogg",
		"media/huruf j.ogg",
		"media/huruf k.ogg",
		"media/huruf l.ogg",
		"media/huruf m.ogg",
		"media/huruf n.ogg",
		"media/huruf o.ogg",
		"media/huruf p.ogg",
		"media/huruf q.ogg",
		"media/huruf r.ogg",
		"media/huruf s.ogg",
		"media/huruf t.ogg",
		"media/huruf u.ogg",
		"media/huruf v.ogg",
		"media/huruf w.ogg",
		"media/huruf x.ogg",
		"media/huruf y.ogg",
		"media/huruf z.ogg",
		"media/pembukaan level 1.ogg",
		"media/lvl 2 huruf a kecil.ogg",
		"media/lvl 2 huruf h besar.ogg",
		"media/lvl 2 huruf j kecil.ogg",
		"media/lvl 2 huruf r besar.ogg",
		"media/pembukaan level 2.ogg",
		"media/lvl 3 buku.ogg",
		"media/lvl 3 mata.ogg",
		"media/lvl 3 meja.ogg",
		"media/pembukaan level 3.ogg",
		"media/level 3.ogg",
		"media/melanjutkan angka 1,2,3,4.ogg",
		"media/melanjutkan angka 2,3,4,5.ogg",
		"media/pembukaan lvl 2.ogg",
		"media/pembukaan lvl 3.ogg",
		"media/1.ogg",
		"media/10.ogg",
		"media/2.ogg",
		"media/3.ogg",
		"media/4.ogg",
		"media/5.ogg",
		"media/6.ogg",
		"media/7.ogg",
		"media/8.ogg",
		"media/9.ogg",
		"media/menghitung dinosaurus .ogg",
		"media/menghitung ikan.ogg",
		"media/menghitung monyet.ogg",
		"media/pembukaan level 1 angka.ogg",
		"media/salah.ogg",
		"media/good job.ogg",
		"media/suara tombol ketika di klik.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}